//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibia.Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7171")]
        public int Network_Port_LoginServer {
            get {
                return ((int)(this["Network_Port_LoginServer"]));
            }
            set {
                this["Network_Port_LoginServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7172")]
        public int Network_Port_GameServer {
            get {
                return ((int)(this["Network_Port_GameServer"]));
            }
            set {
                this["Network_Port_GameServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\items\\items.xml")]
        public string Items_Xml {
            get {
                return ((string)(this["Items_Xml"]));
            }
            set {
                this["Items_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\items\\items.otb")]
        public string Items_Otb {
            get {
                return ((string)(this["Items_Otb"]));
            }
            set {
                this["Items_Otb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\world\\forgotten.otbm")]
        public string Map_Otb {
            get {
                return ((string)(this["Map_Otb"]));
            }
            set {
                this["Map_Otb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\world\\forgotten-house.xml")]
        public string Houses_Xml {
            get {
                return ((string)(this["Houses_Xml"]));
            }
            set {
                this["Houses_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\world\\forgotten-spawn.xml")]
        public string Spawns_Xml {
            get {
                return ((string)(this["Spawns_Xml"]));
            }
            set {
                this["Spawns_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\outfits.xml")]
        public string Outfits_Xml {
            get {
                return ((string)(this["Outfits_Xml"]));
            }
            set {
                this["Outfits_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\mounts.xml")]
        public string Mounts_Xml {
            get {
                return ((string)(this["Mounts_Xml"]));
            }
            set {
                this["Mounts_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\channels\\channels.xml")]
        public string Channels_Xml {
            get {
                return ((string)(this["Channels_Xml"]));
            }
            set {
                this["Channels_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\monsters\\monsters.xml")]
        public string Monsters_Xml {
            get {
                return ((string)(this["Monsters_Xml"]));
            }
            set {
                this["Monsters_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\spells\\spells.xml")]
        public string Spells_Xml {
            get {
                return ((string)(this["Spells_Xml"]));
            }
            set {
                this["Spells_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\npcs\\npcs.xml")]
        public string Npcs_Xml {
            get {
                return ((string)(this["Npcs_Xml"]));
            }
            set {
                this["Npcs_Xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\data\\vocations.xml")]
        public string Vocations_Xml {
            get {
                return ((string)(this["Vocations_Xml"]));
            }
            set {
                this["Vocations_Xml"] = value;
            }
        }
    }
}
